openapi: 3.0.0
info:
  title: task-management
  description:
  version: 1.0.0

servers:
  - url: http://localhost:3000/api

paths:
  /users:
    post:
      summary: Create a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    # format: int64
                    example: 4
                  username:
                    type: string
                    example: Obama
        "400":
          description: The specified user ID is invalid (not a number).
